"""Hatch build hook that generates the aspected_client package from openapi.json."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from collections import Counter
from copy import deepcopy
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class GenerateClientBuildHook(BuildHookInterface):
    """Custom build hook that generates client code from the OpenAPI spec before building."""

    PLUGIN_NAME = "generate-client"

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        """Run code generation before build."""
        root = Path(self.root)
        self._root = root
        self._templates_dir = root / "templates"
        self._openapi_path = root / "openapi.json"
        self._output_dir = root / "src" / "aspected_client"
        self._model_output = self._output_dir / "model.py"
        self._client_output = self._output_dir / "client.py"
        self._init_output = self._output_dir / "__init__.py"
        self._file_header = "# This file is automatically generated, do not edit this file"

        spec = json.loads(self._openapi_path.read_text())
        preprocessed = _preprocess_spec(spec)

        self._ensure_package_dir()
        self._generate_models(preprocessed)
        self._generate_client(spec)
        self._generate_init()
        self._run_formatters()
        self._apply_patches()

    def _ensure_package_dir(self) -> None:
        """Create the target package directory and py.typed marker if needed."""
        self._output_dir.mkdir(parents=True, exist_ok=True)
        py_typed = self._output_dir / "py.typed"
        if not py_typed.exists():
            py_typed.write_text("")

    def _generate_models(self, spec: dict) -> None:
        """Generate model.py from the preprocessed OpenAPI spec using datamodel-codegen."""
        spec_json = json.dumps(spec)

        cmd = [
            sys.executable,
            "-m",
            "datamodel_code_generator",
            "--output",
            str(self._model_output),
            "--input-file-type",
            "openapi",
            "--preset",
            "practical-py312-20260619",
            "--openapi-scopes",
            "schemas",
            "paths",
            "--use-title-as-name",
            "--use-type-alias",
            "--custom-file-header",
            self._file_header,
            "--formatters",
            "ruff-check",
            "ruff-format",
        ]
        result = subprocess.run(
            cmd,
            cwd=self._root,
            input=spec_json,
            text=True,
            capture_output=True,
        )
        if result.returncode != 0:
            sys.stderr.write(result.stdout)
            sys.stderr.write(result.stderr)
            result.check_returncode()

    def _generate_client(self, spec: dict) -> None:
        """Generate client.py from the OpenAPI spec using the Jinja2 template."""
        from jinja2 import Environment, FileSystemLoader

        operations = _build_operations(spec)

        imports: set[str] = set()
        for op in operations:
            if op["request_class"]:
                imports.add(op["request_class"])
            imports.add(op["response_class"])

        sorted_imports = sorted(imports)

        env = Environment(
            loader=FileSystemLoader(str(self._templates_dir)),
            keep_trailing_newline=True,
        )
        template = env.get_template("client.py.j2")

        rendered = template.render(
            operations=operations,
            imports=sorted_imports,
            header=self._file_header,
        )

        self._client_output.write_text(rendered)

    def _generate_init(self) -> None:
        """Generate __init__.py that re-exports the client and all model classes."""
        from jinja2 import Environment, FileSystemLoader

        model_source = self._model_output.read_text()
        model_imports = sorted(
            re.findall(r"^(?:class|type) (\w+)[\s(=]", model_source, re.MULTILINE)
        )

        env = Environment(
            loader=FileSystemLoader(str(self._templates_dir)),
            keep_trailing_newline=True,
        )
        template = env.get_template("__init__.py.j2")

        rendered = template.render(model_imports=model_imports, header=self._file_header)

        self._init_output.write_text(rendered)

    def _run_formatters(self) -> None:
        """Run ruff format and check --fix on the generated files."""
        generated_files = [
            str(self._client_output),
            str(self._model_output),
            str(self._init_output),
        ]

        result = subprocess.run(
            ["ruff", "format", *generated_files],
            cwd=self._root,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            sys.stderr.write(result.stdout)
            sys.stderr.write(result.stderr)
            result.check_returncode()

        result = subprocess.run(
            ["ruff", "check", "--fix", "--ignore", "E501", *generated_files],
            cwd=self._root,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            sys.stderr.write(result.stdout)
            sys.stderr.write(result.stderr)
            result.check_returncode()

    def _apply_patches(self) -> None:
        """Apply all patch files from the patches directory.

        Uses the pure-Python ``patch-ng`` library instead of ``git apply`` or
        the system ``patch`` binary. This avoids two portability problems:

        - Build backends (e.g. uv) may build in an isolated temp directory
          that contains only a sentinel ``.git`` file (not a real
          repository), which makes ``git apply`` fail with "not a git
          repository".
        - The ``patch`` command-line utility isn't reliably available on
          Windows.

        ``patch-ng`` has no such dependencies and works identically on all
        platforms.
        """
        import patch_ng

        patches_dir = self._root / "patches"
        if not patches_dir.is_dir():
            return

        for patch_file in sorted(patches_dir.glob("*.patch")):
            patch_set = patch_ng.fromfile(str(patch_file))
            if not patch_set:
                raise RuntimeError(f"Failed to parse patch {patch_file.name}")
            if not patch_set.apply(root=str(self._root)):
                raise RuntimeError(f"Failed to apply patch {patch_file.name}")


# ---------------------------------------------------------------------------
# Helpers (moved from generate_client.py)
# ---------------------------------------------------------------------------


def _snake_case(name: str) -> str:
    """Convert camelCase operationId to snake_case method name."""
    s1 = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def _pascal_case(name: str) -> str:
    """Convert operationId to PascalCase (for Request/Response class names)."""
    return name[0].upper() + name[1:]


def _openapi_type_to_python(schema: dict) -> str:
    """Map an OpenAPI schema type to a Python type hint string."""
    t = schema.get("type", "string")
    mapping = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
    }
    return mapping.get(t, "str")


def _build_operations(spec: dict) -> list[dict]:
    """Extract operation metadata from the OpenAPI spec."""
    ops: list[dict] = []
    params_registry = spec.get("components", {}).get("parameters", {})

    for path, methods in spec.get("paths", {}).items():
        for http_method, details in methods.items():
            if http_method not in ("get", "post", "put", "delete", "patch"):
                continue

            operation_id = details["operationId"]
            method_name = _snake_case(operation_id)
            summary = details.get("summary", "")
            description = details.get("description", "")

            path_params: list[dict] = []
            query_params: list[dict] = []

            for param in details.get("parameters", []):
                if "$ref" in param:
                    ref_name = param["$ref"].split("/")[-1]
                    param = params_registry[ref_name]

                schema = param.get("schema", {})
                p = {
                    "name": param["name"],
                    "python_name": _snake_case(param["name"]),
                    "required": param.get("required", False),
                    "type": _openapi_type_to_python(schema),
                    "description": param.get("description", ""),
                }
                if param["in"] == "path":
                    path_params.append(p)
                elif param["in"] == "query":
                    query_params.append(p)

            has_body = "requestBody" in details
            request_class = f"{_pascal_case(operation_id)}Payload" if has_body else None
            response_class = f"{_pascal_case(operation_id)}Result"

            url_template = path
            for pp in path_params:
                url_template = url_template.replace(
                    "{" + pp["name"] + "}", "{" + pp["python_name"] + "}"
                )

            ops.append(
                {
                    "method_name": method_name,
                    "http_method": http_method,
                    "url_template": url_template,
                    "path_params": path_params,
                    "query_params": query_params,
                    "has_body": has_body,
                    "request_class": request_class,
                    "response_class": response_class,
                    "summary": summary,
                    "description": description,
                }
            )

    return ops


# ---------------------------------------------------------------------------
# OpenAPI spec preprocessing
# ---------------------------------------------------------------------------


def _to_pascal_case(name: str) -> str:
    """Convert a field name (camelCase or snake_case) to PascalCase."""
    if "_" in name:
        return "".join(part.capitalize() for part in name.split("_"))
    return name[0].upper() + name[1:]


def _is_schema_node(node: dict) -> bool:
    """Check if a dict is an OpenAPI schema that would generate a named type."""
    if not isinstance(node, dict):
        return False
    if node.get("type") == "object" and "properties" in node:
        return True
    return "allOf" in node


def _ensure_titles(node: dict | list, field_name: str | None = None) -> None:
    """Walk schemas and ensure every object/array schema has a title."""
    if isinstance(node, list):
        for item in node:
            if isinstance(item, (dict, list)):
                _ensure_titles(item, field_name)
        return

    if not isinstance(node, dict):
        return

    if "$ref" in node:
        return

    if _is_schema_node(node) and "title" not in node and field_name:
        node["title"] = _to_pascal_case(field_name)

    if "properties" in node and isinstance(node["properties"], dict):
        for prop_name, prop_schema in node["properties"].items():
            if isinstance(prop_schema, dict):
                _ensure_titles(prop_schema, prop_name)

    if "items" in node and isinstance(node["items"], dict):
        _ensure_titles(node["items"], field_name)

    for keyword in ("allOf", "oneOf", "anyOf"):
        if keyword in node and isinstance(node[keyword], list):
            for item in node[keyword]:
                if isinstance(item, dict):
                    _ensure_titles(item, field_name)


def _ensure_titles_in_spec(spec: dict) -> None:
    """Add missing titles to all schemas in paths and components/schemas."""
    schemas = spec.get("components", {}).get("schemas", {})
    for schema_name, schema_obj in schemas.items():
        if isinstance(schema_obj, dict):
            if _is_schema_node(schema_obj) and "title" not in schema_obj:
                schema_obj["title"] = schema_name
            _ensure_titles(schema_obj, schema_name)

    for _path, methods in spec.get("paths", {}).items():
        if not isinstance(methods, dict):
            continue
        for _method, operation in methods.items():
            if not isinstance(operation, dict):
                continue
            req_body = (
                operation.get("requestBody", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema")
            )
            if isinstance(req_body, dict):
                _ensure_titles(req_body, None)

            for _status, response in operation.get("responses", {}).items():
                if not isinstance(response, dict):
                    continue
                resp_schema = response.get("content", {}).get("application/json", {}).get("schema")
                if isinstance(resp_schema, dict):
                    _ensure_titles(resp_schema, None)


def _collect_titles(node: dict | list, parent_title: str | None = None) -> list[dict]:
    """Walk the spec tree and collect all objects that have a 'title' key."""
    results: list[dict] = []
    if isinstance(node, dict):
        title_val = node.get("title")
        current_title = title_val if isinstance(title_val, str) else None
        effective_parent = parent_title
        if current_title is not None:
            results.append(
                {
                    "obj": node,
                    "title": current_title,
                    "parent_title": parent_title,
                }
            )
            effective_parent = current_title
        for value in node.values():
            if isinstance(value, (dict, list)):
                results.extend(_collect_titles(value, effective_parent))
    elif isinstance(node, list):
        for item in node:
            if isinstance(item, (dict, list)):
                results.extend(_collect_titles(item, parent_title))
    return results


def _preprocess_spec(spec: dict) -> dict:
    """Rename titles: Request→Payload, Response→Result, then resolve collisions."""
    spec = deepcopy(spec)

    _ensure_titles_in_spec(spec)

    def _collect_from_spec(s: dict) -> list[dict]:
        entries: list[dict] = []
        if "paths" in s:
            entries.extend(_collect_titles(s["paths"]))
        schemas = s.get("components", {}).get("schemas")
        if schemas:
            entries.extend(_collect_titles(schemas))
        return entries

    # Step 1: Rename suffixes
    entries = _collect_from_spec(spec)
    for entry in entries:
        title = entry["obj"]["title"]
        if title.endswith("Request"):
            entry["obj"]["title"] = title[: -len("Request")] + "Payload"
        elif title.endswith("Response"):
            entry["obj"]["title"] = title[: -len("Response")] + "Result"

    # Step 2: Set titles on request/response schemas using operationId
    for _path, methods in spec.get("paths", {}).items():
        if not isinstance(methods, dict):
            continue
        for _method, operation in methods.items():
            if not isinstance(operation, dict):
                continue
            op_id = operation.get("operationId")
            if not op_id:
                continue
            pascal = _pascal_case(op_id)

            req_schema = (
                operation.get("requestBody", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema")
            )
            if isinstance(req_schema, dict):
                req_schema["title"] = f"{pascal}Payload"

            resp_schema = (
                operation.get("responses", {})
                .get("200", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema")
            )
            if isinstance(resp_schema, dict):
                resp_schema["title"] = f"{pascal}Result"

    # Step 3: Resolve collisions iteratively
    while True:
        entries = _collect_from_spec(spec)
        title_counts = Counter(e["title"] for e in entries)
        colliding_titles = {t for t, count in title_counts.items() if count > 1}

        if not colliding_titles:
            break

        for entry in entries:
            if entry["title"] in colliding_titles:
                parent = entry["parent_title"]
                if parent:
                    entry["obj"]["title"] = parent + entry["title"]

    return spec
