# This file is automatically generated, do not edit this file

"""Aspected client -- a simple httpx-based Python client for the Aspected Database API."""

from __future__ import annotations

import httpx

from .model import (
    CreateIndexPayload,
    CreateIndexResult,
    DeleteIndexResult,
    ErrorResult,
    GetDocResult,
    GetDocsResult,
    GetIndexResult,
    ListIndexesResult,
    SearchIndexPayload,
    SearchIndexResult,
    UploadDocsPayload,
    UploadDocsResult,
)


class AspectedError(Exception):
    """Raised when the Aspected API returns a non-success HTTP response.

    Attributes
    ----------
    status : int
        HTTP status code.
    status_text : str
        HTTP reason phrase.
    error : str | None
        Server-provided error message, if available.
    """

    def __init__(self, status: int, status_text: str, error: str | None = None) -> None:
        self.status = status
        self.status_text = status_text
        self.error = error
        message = f"{status} {status_text}"
        if error:
            message += f": {error}"
        super().__init__(message)


class AspectedClient:
    """Synchronous client for the Aspected database.

    Parameters
    ----------
    url : str
        Base URL of the Aspected database server (e.g. ``"http://localhost:8080"``).
    """

    def __init__(self, url: str, **httpx_kwargs) -> None:
        self._base_url = url.rstrip("/")
        self._client = httpx.Client(base_url=self._base_url, **httpx_kwargs)

    # ------------------------------------------------------------------
    # Generated API Methods
    # ------------------------------------------------------------------

    def upload_docs(
        self,
        index_name: str,
        body: UploadDocsPayload,
    ) -> UploadDocsResult:
        """Creates, updates, and deletes documents in a single transactional request."""
        resp = self._client.post(
            f"/indexes/{index_name}/docs",
            content=body.model_dump_json(by_alias=True, exclude_none=True),
            headers={"Content-Type": "application/json"},
        )
        if not resp.is_success:
            error_msg: str | None = None
            try:
                error_result = ErrorResult.model_validate(resp.json())
                error_msg = error_result.error
            except Exception:
                pass
            raise AspectedError(resp.status_code, resp.reason_phrase, error_msg)
        return UploadDocsResult.model_validate(resp.json())

    def get_docs(
        self,
        index_name: str,
        page: int | None = None,
        limit: int | None = None,
        ids: list | None = None,
    ) -> GetDocsResult:
        """Returns a paginated list of documents stored in an index."""
        params: dict = {}
        if page is not None:
            params["page"] = page
        if limit is not None:
            params["limit"] = limit
        if ids is not None:
            params["ids"] = ids
        resp = self._client.get(
            f"/indexes/{index_name}/docs",
            params=params,
        )
        if not resp.is_success:
            error_msg: str | None = None
            try:
                error_result = ErrorResult.model_validate(resp.json())
                error_msg = error_result.error
            except Exception:
                pass
            raise AspectedError(resp.status_code, resp.reason_phrase, error_msg)
        return GetDocsResult.model_validate(resp.json())

    def get_doc(
        self,
        index_name: str,
        doc_id: str,
    ) -> GetDocResult:
        """Returns a single document by ID from an index."""
        resp = self._client.get(
            f"/indexes/{index_name}/docs/{doc_id}",
        )
        if not resp.is_success:
            error_msg: str | None = None
            try:
                error_result = ErrorResult.model_validate(resp.json())
                error_msg = error_result.error
            except Exception:
                pass
            raise AspectedError(resp.status_code, resp.reason_phrase, error_msg)
        return GetDocResult.model_validate(resp.json())

    def list_indexes(
        self,
        page: int | None = None,
        limit: int | None = None,
    ) -> ListIndexesResult:
        """Returns a paginated list of all available indexes."""
        params: dict = {}
        if page is not None:
            params["page"] = page
        if limit is not None:
            params["limit"] = limit
        resp = self._client.get(
            "/indexes",
            params=params,
        )
        if not resp.is_success:
            error_msg: str | None = None
            try:
                error_result = ErrorResult.model_validate(resp.json())
                error_msg = error_result.error
            except Exception:
                pass
            raise AspectedError(resp.status_code, resp.reason_phrase, error_msg)
        return ListIndexesResult.model_validate(resp.json())

    def get_index(
        self,
        index_name: str,
    ) -> GetIndexResult:
        """Returns detailed metadata about a single index, including its schema and HNSW parameters."""
        resp = self._client.get(
            f"/indexes/{index_name}",
        )
        if not resp.is_success:
            error_msg: str | None = None
            try:
                error_result = ErrorResult.model_validate(resp.json())
                error_msg = error_result.error
            except Exception:
                pass
            raise AspectedError(resp.status_code, resp.reason_phrase, error_msg)
        return GetIndexResult.model_validate(resp.json())

    def create_index(
        self,
        index_name: str,
        body: CreateIndexPayload,
    ) -> CreateIndexResult:
        """Creates a new index with the given name and configuration."""
        resp = self._client.put(
            f"/indexes/{index_name}",
            content=body.model_dump_json(by_alias=True, exclude_none=True),
            headers={"Content-Type": "application/json"},
        )
        if not resp.is_success:
            error_msg: str | None = None
            try:
                error_result = ErrorResult.model_validate(resp.json())
                error_msg = error_result.error
            except Exception:
                pass
            raise AspectedError(resp.status_code, resp.reason_phrase, error_msg)
        return CreateIndexResult.model_validate(resp.json())

    def delete_index(
        self,
        index_name: str,
    ) -> DeleteIndexResult:
        """Deletes an index and removes its persisted data from disk."""
        resp = self._client.delete(
            f"/indexes/{index_name}",
        )
        if not resp.is_success:
            error_msg: str | None = None
            try:
                error_result = ErrorResult.model_validate(resp.json())
                error_msg = error_result.error
            except Exception:
                pass
            raise AspectedError(resp.status_code, resp.reason_phrase, error_msg)
        return DeleteIndexResult.model_validate(resp.json())

    def search_index(
        self,
        index_name: str,
        body: SearchIndexPayload,
    ) -> SearchIndexResult:
        """Performs a k-nearest-neighbour search against an existing index."""
        resp = self._client.post(
            f"/indexes/{index_name}/search",
            content=body.model_dump_json(by_alias=True, exclude_none=True),
            headers={"Content-Type": "application/json"},
        )
        if not resp.is_success:
            error_msg: str | None = None
            try:
                error_result = ErrorResult.model_validate(resp.json())
                error_msg = error_result.error
            except Exception:
                pass
            raise AspectedError(resp.status_code, resp.reason_phrase, error_msg)
        return SearchIndexResult.model_validate(resp.json())

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def close(self) -> None:
        """Close the underlying HTTP connection pool."""
        self._client.close()

    def __enter__(self) -> AspectedClient:
        return self

    def __exit__(self, *args) -> None:
        self.close()
