# This file is automatically generated, do not edit this file

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class SuccessResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    time: float | None = None
    """Time taken to process the request in milliseconds."""
    status: str | None = None
    """Status message indicating success."""


class ErrorResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    error: str | None = None
    """Human-readable error message."""


class Aspect(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    type: str
    path: str
    settings: dict[str, Any]
    multiplier: float | None = None


class DocEntry(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    doc: dict[str, Any]
    vector: list[float]
    access_list: Annotated[list[str] | None, Field(alias="accessList")] = None


class Duplicate(StrEnum):
    replace_ = "Replace"
    ignore = "Ignore"
    fail = "Fail"


class UpsertOperationPolicy(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    duplicate: Duplicate | None = None


class UpsertOperation(BaseModel):
    """Create or update a document."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    doc: dict[str, object]
    vectors: dict[str, list[float]] | None = None
    access_list: Annotated[list[str] | None, Field(alias="accessList")] = None
    policy: Annotated[UpsertOperationPolicy | None, Field(title="UpsertOperationPolicy")] = None


class Missing(StrEnum):
    ignore = "Ignore"
    fail = "Fail"


class DeleteOperationPolicy(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    missing: Missing | None = None


class DeleteOperation(BaseModel):
    """Delete a document."""

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    doc: None
    policy: Annotated[DeleteOperationPolicy | None, Field(title="DeleteOperationPolicy")] = None


class UploadDocsPayloadPolicy(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    duplicate: Duplicate = Duplicate.replace_
    missing: Missing = Missing.ignore


class UploadDocsPayload(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[UpsertOperation | DeleteOperation]
    policy: Annotated[UploadDocsPayloadPolicy | None, Field(title="UploadDocsPayloadPolicy")] = (
        None
    )


class UpdateResult(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    created: list[str]
    updated: list[str]
    deleted: list[str]


class UploadDocsResult(SuccessResult):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Annotated[UpdateResult, Field(title="UpdateResult")]


class GetDocsResult(SuccessResult):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    total: int
    page: int
    limit: int
    data: list[DocEntry]


class GetDocResult(SuccessResult):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: DocEntry


class ListIndexResultData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str


class ListIndexesResult(SuccessResult):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    total: int
    page: int
    limit: int
    data: list[ListIndexResultData]


class DistanceType(StrEnum):
    manhattan = "Manhattan"
    euclidean = "Euclidean"
    dot_product = "DotProduct"
    cosine = "Cosine"


class Hnsw(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    m: Annotated[int, Field(alias="M")]
    mmax: Annotated[int, Field(alias="Mmax")]
    mmax0: Annotated[int, Field(alias="Mmax0")]
    m_l: Annotated[float, Field(alias="mL")]
    ef_construction: Annotated[int, Field(alias="efConstruction")]
    ef_search: Annotated[int, Field(alias="efSearch")]
    extend_candidates: Annotated[bool, Field(alias="extendCandidates")]
    keep_pruned_connections: Annotated[bool, Field(alias="keepPrunedConnections")]
    max_store_size: Annotated[int, Field(alias="maxStoreSize")]


class Index(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    id_size: Annotated[int, Field(alias="idSize")]
    num_dims: Annotated[int, Field(alias="numDims")]
    distance_type: Annotated[DistanceType, Field(alias="distanceType")]
    schema_: Annotated[list[Aspect], Field(alias="schema")]
    hnsw: Annotated[Hnsw, Field(title="Hnsw")]


class GetIndexResult(SuccessResult):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Annotated[Index, Field(title="Index")]


class HNSWConfig(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    m: Annotated[int | None, Field(alias="M")] = None
    mmax: Annotated[int | None, Field(alias="Mmax")] = None
    mmax0: Annotated[int | None, Field(alias="Mmax0")] = None
    m_l: Annotated[float | None, Field(alias="mL")] = None
    ef_construction: Annotated[int | None, Field(alias="efConstruction")] = None
    ef_search: Annotated[int | None, Field(alias="efSearch")] = None
    extend_candidates: Annotated[bool | None, Field(alias="extendCandidates")] = None
    keep_pruned_connections: Annotated[bool | None, Field(alias="keepPrunedConnections")] = None
    max_store_size: Annotated[int | None, Field(alias="maxStoreSize")] = None


class CreateIndexPayload(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id_size: Annotated[int, Field(alias="idSize")]
    distance_type: Annotated[DistanceType | None, Field(alias="distanceType")] = None
    schema_: Annotated[list[Aspect], Field(alias="schema")]
    hnsw: Annotated[HNSWConfig | None, Field(title="HNSWConfig")] = None


class CreateIndexResultData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    created: bool


class CreateIndexResult(SuccessResult):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Annotated[CreateIndexResultData, Field(title="CreateIndexResultData")]


class DeleteIndexResultData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    deleted: bool


class DeleteIndexResult(SuccessResult):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Annotated[DeleteIndexResultData, Field(title="DeleteIndexResultData")]


class QueryVector(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_raw: Annotated[list[float], Field(alias="$raw")]


class QuerySearch(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    k: Annotated[int, Field(ge=1)]
    """Number of nearest neighbours to return."""
    query: dict[str, QueryVector | Any]
    """
    Map of aspect names to query values. Each value can be a primitive (string, number, boolean), object, array, null, or a raw vector specified as `{"$raw": [number, ...]}`.

    """
    weights: dict[str, float] | None = None
    """Optional map of aspect names to weight multipliers."""
    access_filter: Annotated[list[str | None] | None, Field(alias="accessFilter")] = None
    """Optional access filter list. Null entries are permitted."""
    with_docs: Annotated[bool, Field(alias="withDocs")] = False
    """Whether to include the stored document in each result."""
    with_vectors: Annotated[bool, Field(alias="withVectors")] = False
    """Whether to include the vector in each result."""
    with_explanation: Annotated[bool, Field(alias="withExplanation")] = False
    """Whether to include an explanation of search aspects in each result."""


class DocSearch(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    k: Annotated[int, Field(ge=1)]
    """Number of nearest neighbours to return."""
    doc: dict[str, Any]
    """A document object to use as the query."""
    weights: dict[str, float] | None = None
    """Optional map of aspect names to weight multipliers."""
    access_filter: Annotated[list[str | None] | None, Field(alias="accessFilter")] = None
    """Optional access filter list. Null entries are permitted."""
    with_docs: Annotated[bool, Field(alias="withDocs")] = False
    """Whether to include the stored document in each result."""
    with_vectors: Annotated[bool, Field(alias="withVectors")] = False
    """Whether to include the vector in each result."""
    with_explanation: Annotated[bool, Field(alias="withExplanation")] = False
    """Whether to include an explanation of search aspects in each result."""


type SearchIndexPayload = Annotated[QuerySearch | DocSearch, Field(title="SearchIndexPayload")]


class SearchResultExplanation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    value: Any
    distance: float | None = None


class SearchResultRow(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    distance: float
    vector: list[float] | None = None
    doc: dict[str, Any] | None = None
    explanation: list[SearchResultExplanation] | None = None


class SearchIndexResult(SuccessResult):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[SearchResultRow]
